version: '3.8'
services:
  app:
    container_name: json-translate
    image: json-translate:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3799:3000"
    restart: always